# Generated by Django 4.2 on 2025-02-08 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_year', models.DateField()),
                ('genre', models.CharField(choices=[('HipHop', 'HipHop'), ('Rock', 'Rock'), ('Reggae', 'Reggae'), ('Jazz', 'Jazz'), ('Pasillo', 'Pasillo'), ('Bachata', 'Bachata')], max_length=30)),
                ('album_cover', models.ImageField(upload_to='album_images')),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='album_manager.artist')),
            ],
        ),
    ]
