# Generated by Django 4.2 on 2025-02-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_manager', '0002_alter_album_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_cover',
            field=models.ImageField(upload_to='examen-parcial-3-Xavier1812/album_manager/media'),
        ),
    ]
